[tool.black]
line-length = 79
target-version = ['py38']
max-line-length = 79
exclude = '''
(
    generated
)
'''

[tool.isort]
known_third_party = ["torch", "pyspark", "PIL", "pytest"]
known_first_party = "rikai"
order_by_type = false
skip = "python/rikai/spark/sql/generated"